%% =============================================================================================
% ================================= Machine Learning Software ==================================
% ================================ Presented by: Reza Saadatyar ================================
% ======================================= 2018-2019 ============================================

function help(tab6)
uicontrol('parent',tab6,'style','text','string','List of Abbreviations:','unit','norm','Position',...
[0.06 0.9 0.9 0.1],'Fontweight','bold','FontSize',20,'FontName','Times New Roman');
uicontrol('parent',tab6,'style','text','string',{'Filtering:';'Sampling frequency (Fs)';...
'lower cutoff frequency (Flow)';'higher cutoff frequency (Fhigh)';'Passband ripple (Rp)';...
'Stopband attenuation (Rs)'},'unit','norm','Position',[0.02 0.6 0.2 0.3],'Fontweight',...
'bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left',...
'ForegroundColor',[0.49 0.18 0.56]);
uicontrol('parent',tab6,'style','text','string',{'Feature Exraction:';'Average amplitude change (AAC)';...
'Difference absolute standard deviation value (DASDV)';'Median';'Mean absolute deviation (MAD)';...
'Mean absolute value (MAV)';'Mean';'Modified Mean Absolute Value (MMAV)';'Maximum Fractal Length (MFL)';...
'Myopulse percentage rate (MYOP)';'Integrated';'Root Mean Square (RMS)';'Std';'Simple Square Integral (SSI)';...
'Slope sign changes (SSC)';'Skewness';'Kurtosis';'Zero crossing (ZC)';'Variance (VAR)';'V-Order 2';...
'Waveform length (WL)';'Wavelet: Soft (S); Hard (h)'},'unit','norm','Position',[0.2 0.17 0.2 0.73],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left',...
'ForegroundColor',[0.64 0.08 0.18]);
uicontrol('parent',tab6,'style','text','string',{'Feature Seletion:';'Principle Component Analysis (PCA)';...
'Fisher s Discriminate Analysis (FDA)'; 'False Discovery Rate (FDR)';'Mutual Information';'Ttest'; ...
'ANOVA'},'unit','norm','Position',...
[0.41 0.4 0.2 0.5],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'HorizontalAlignment','left','ForegroundColor','m');
uicontrol('parent',tab6,'style','text','string',{'Classification & Clustring:';'Multi-Layer Perceptron (MLP)';...
'Support Vector Machine (SVM)';'K-Nearest Neighbors (KNN)';'Principal component analysis (PCA)';
'Learning Vector Quantization (LVQ)'; 'Linear Discriminant Analysis (LDA)';'Radial Basis Function (RBF)'; ...
'Probabilistic Neural Network (PNN)'; 'Extreme Learning Machine (ELM)';'Fuzzy C-Means Clustering (FCM)';...
'Decision Tree (DT)';'Bayesian';'K-means'},'unit','norm','Position',[0.62 0.5 0.2 0.41],...
'HorizontalAlignment','left','ForegroundColor','b','FontSize',12,'Fontweight','bold','FontName','Times New Roman');
uicontrol('parent',tab6,'style','text','string',{'Performance:';'Accuracy';'Sensitivity';'Specificity';...
'Precision';'Matthews Correlation Coefficient (MCC)';'F-score'},'unit','norm','Position',...
[0.85 0.5 0.15 0.4],'Fontweight','bold','FontSize',12,'FontName','Times New Roman','HorizontalAlignment','left','ForegroundColor','k');
end

 

