%% =============================================================================================
% ================================= Machine Learning Software ==================================
% ================================ Presented by: Reza Saadatyar ================================
% ======================================= 2018-2019 ============================================

function machine_learning_software
clc; clear; close all;
S.fig=figure('NumberTitle','off','Name','','MenuBar','none','ToolBar','none','Resize','off',...
'Color',0.94*[1 1 1],'Units','normalized','Position',[0.02 0.011 0.97 0.95]);

%% ======================================= Introduction ========================================
tg = uitabgroup;
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="k"><b> Software Outline </font></html>');
S.start=uipanel('parent',tab1,'Title','','unit','norm','Position',[0 0 1 1],'Fontweight',...
'bold','FontSize',16,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.start,'style','text','string','Machine Learning Software','unit','norm',...
'Position',[0.18 0.95 0.65 0.05],'Fontweight','bold','FontSize',20,'FontName','Times New Roman','FontAngle','italic');
S.t1=uicontrol('parent',S.start,'style','text','string',...
{'We have developed an automated machine learning software (MLS) based graphical user interface (GUI) in Matlab for general biomedical signal',...
'processing. Specifically, electroencephalography (EEG), electrocardiography (ECG) and electromyography (EMG) signals can be processed and',...
'analyzed by the developed software. The MLS includes tools for filter design and analysis, feature extraction (time-frequency domains) methods,',...
'dimensionality reduction and artificial neural network-based machine learning (ML) algorithms. At first, each biological signal goes through',...
'preprocessing steps including noise removal and segmentation. Then, the signal features that have been shown to be highly relevant to a better',...
'category discrimination in an intended application are extracted. Moreover, these extracted features are fed to classification and clustering algorithms',...
'for detection and identification. Finally, the MLS presents Wavelet transforms for data analysis based on the level of decomposition and threshold',...
'value chosen. This intuitive tool can also be utilized for training in biomedical engineering education due to its easy-to-use and easy-to-learn. The',...
'package currently contains six different steps:'},'unit','norm','Position',[0.08 0.675 0.85 0.28],'FontSize',14,'FontName','Times New Roman');
if exist('Image\BlockDiagram.jpg','file')~=0;a=axes('Parent',S.start,'unit','norm','position',[0.05 0.35 0.9 0.33]);
uistack(a,'bottom');X=imread('Image\BlockDiagram.jpg');imagesc(X);a.Color=0.94*[1 1 1];
a.XColor=0.94*[1 1 1];a.YColor=0.94*[1 1 1];a.XTick=[];a.YTick=[];
end
if exist('Image\ListStep.jpg','file')~=0;a=axes('Parent',S.start,'unit','norm','position',[0.07 0 0.8 0.37]);
uistack(a,'bottom');X=imread('Image\ListStep.jpg');imagesc(X);a.Color=0.94*[1 1 1];a.XColor=0.94*[1 1 1];
a.YColor=0.94*[1 1 1];a.XTick=[];a.YTick=[];
end

%% ========================================== Load Data ========================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="red"><b> Load & Filtering</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 1','unit',...
'norm','Position',[0.005 0.96 0.37 0.036],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.8 0.8 0.8]);
S.L1=uipanel('parent',tab1,'Title','Load Data','unit','norm','Position',[0.005 0.41 0.37 0.55],...
'BorderWidth',2,'FontSize',12,'FontName','Times New Roman','Fontweight','bold', 'ShadowColor','k');
S.L2=uipanel('parent',S.L1,'Title','','unit','norm','Position',...
[0.012 0.8 0.98 0.2],'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.load=uicontrol('parent',S.L2,'style','pushbutton','string','Open File',...
'unit','norm','Position',[0.02 0.1 0.3 0.7],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Data Name:','unit',...
'norm','Position',[0.37 0.5 0.5 0.38],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.text1=uicontrol('parent',S.L2,'style','text','string','','unit','norm',...
'Position',[0.37 0.28 0.6 0.32],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','BackgroundColor',0.9*[1 1 1],'HorizontalAlignment','left',...
'ForegroundColor','r');
%Param
S.L2=uipanel('parent',S.L1,'Title','Parameters Datat','unit','norm','Position',...
[0.012 0.25 0.98 0.55],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
list=uitable(S.L2,'position',[218 7 237 161],'FontSize',10);
% Clear all data
S.L3=uipanel('parent',S.L2,'Title','Clear Parameters','unit','norm','Position',...
[0.01 0.7 0.46 0.3],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.radio1=uicontrol('parent',S.L3,'style','radio','string','Clear all Param & Figures','unit',...
'norm','Position',[0.008 0.21 1 0.85],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
% Input
S.L3=uipanel('parent',S.L2,'Title','Select Input:','unit','norm','Position',...
[0.01 0.35 0.46 0.35],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.inp=uicontrol('parent',S.L3,'style','popupmenu','string','Select:','unit','norm',...
'Position',[0.02 0.65 0.8 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
% Normalize
S.L3=uipanel('parent',S.L2,'Title','Normalization','unit','norm','Position',...
[0.01 0.05 0.46 0.3],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.radio=uicontrol('parent',S.L3,'style','radio','string','Active','unit',...
'norm','Position',[0.008 0.2 0.8 0.85],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
%Channel
S.L2=uipanel('parent',S.L1,'Title','Select Input Channels:','unit','norm','Position',...
[0.012 0.03 0.98 0.22],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.input=uicontrol('parent',S.L2,'style','popupmenu','string','Select:','unit',...
'norm','Position',[0.009 0 0.28 0.8],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Chi:','unit','norm',...
'Position',[0.42 0.2 0.13 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Chi=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','enable','off',...
'Position',[0.50 0.3 0.15 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','Tooltip','0<Chi<Num(All Ch)-1');
S.t1=uicontrol('parent',S.L2,'style','text','string','Chj:','unit','norm',...
'Position',[0.75 0.2 0.13 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Chj=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','enable','off',...
'Position',[0.83 0.3 0.15 0.52],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','Tooltip','Chi<Chj<=Num(All Ch)');

%% ====================================== Filtering ============================================
S.t1=uicontrol('parent',tab1,'style','text','string','Step 2 (Optional)','unit',...
'norm','Position',[0.385 0.96 0.37 0.036],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.8 0.8 0.8], 'ForegroundColor','r');
S.L1=uipanel('parent',tab1,'Title','Filtering','unit','norm','Position',...
[0.385 0.41 0.37 0.55],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'ShadowColor','k','BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Notch Filter ','unit','norm','Position',...
[0.012 0.845 0.98 0.15],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.notch=uicontrol('parent',S.L2,'style','radio','string','Active','unit','norm',...
'Position',[0.018 0.2 0.8 0.73],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left','value',0);
S.t1=uicontrol('parent',S.L2,'style','text','string','F0 (Hz):','unit',...
'norm','Position',[0.53 0.21 0.8 0.6],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
S.Fnotch=uicontrol('parent',S.L2,'style','edit','string','50','unit',...
'norm','Position',[0.7553 0.2 0.2 0.8],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Design Method','unit','norm','Position',...
[0.012 0.67 0.49 0.17],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.design=uicontrol('parent',S.L2,'style','popupmenu','unit','norm','Fontweight',...
'bold','string',{'Select:';'Moving Average',;'Butter';'Cheby1';'Cheby2';'Ellip'},...
'Position',[0.04 0 0.815 0.9],'FontSize',11,'FontName','Times New Roman');
S.Response=uipanel('parent',S.L1,'Title','Response Type','unit','norm','Position',...
[0.51 0.67 0.48 0.17],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.response=uicontrol('parent',S.Response,'style','popupmenu','unit','norm','Fontweight',...
'bold','Position',[0.04 0 0.86 0.9],'FontSize',11,'FontName','Times New Roman',...
'string',{'Select:';'Lowpass';'Highpass';'Bandpass';'Bandstop'});
S.L2=uipanel('parent',S.L1,'Title','Parameters','unit','norm','Position',...
[0.012 0.195 0.98 0.47],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Fs (Hz):','unit','norm',...
'Position',[0.026 0.81 0.65 0.11],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.fs=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.21 0.76 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','Sampling Frequency');
S.t1=uicontrol('parent',S.L2,'style','text','string','Order:','unit','norm','Position',...
[0.54 0.81 0.65 0.12],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.order=uicontrol('parent',S.L2,'style','edit','string','3','unit','norm','Position',...
[0.75 0.76 0.202 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','Order>0');
S.t1=uicontrol('parent',S.L2,'style','text','string','Flow (Hz):','unit',...
'norm','Position',[0.023 0.498 0.65 0.12],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.fl=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.21 0.45 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Flow>1');
S.t1=uicontrol('parent',S.L2,'style','text','string','Fhigh (Hz):',...
'unit','norm','Position',[0.54 0.492 0.65 0.12],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman','HorizontalAlignment','left');
S.fh=uicontrol('parent',S.L2,'style','edit','string','','unit','norm',...
'Position',[0.75 0.45 0.202 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Fhigh>1');
S.t1=uicontrol('parent',S.L2,'style','text','string','Rp (dB):','unit',...
'norm','Position',[0.023 0.15 0.65 0.12],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.rp=uicontrol('parent',S.L2,'style','edit','string','2','unit','norm',...
'Position',[0.21 0.11 0.21 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Rp>1');
S.t1=uicontrol('parent',S.L2,'style','text','string','Rs (dB):','unit',...
'norm','Position',[0.54 0.16 0.65 0.11],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.rs=uicontrol('parent',S.L2,'style','edit','string','3','unit','norm',...
'Position',[0.75 0.11 0.202 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','Tooltip','Rs>1');
S.L2=uipanel('parent',S.L1,'Title','Window Size','unit','norm','Position',...
[0.012 0.03 0.55 0.17],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Window Length:',...
'unit','norm','Position',[0.033 0.38 0.99 0.43],'Fontweight','bold','FontSize',...
11,'FontName','Times New Roman','HorizontalAlignment','left');
S.window=uicontrol('parent',S.L2,'style','edit','string','3','unit','norm',...
'Position',[0.6 0.2 0.33 0.73],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','Tooltip','Window size>1');
S.L2=uipanel('parent',S.L1,'Title','Plot','unit','norm','Position',...
[0.58 0.03 0.413 0.17],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.display=uicontrol('parent',S.L2,'style','radio','string','Display Plot','unit',...
'norm','Position',[0.05 0.2 0.8 0.73],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
S.ax(1)=uipanel('Parent',tab1,'Title','Figure Raw & Filtered Signals',...
'unit','norm','outerposition',[0.005 0 0.991 0.4],'ShadowColor','k',...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.ax(13)=uipanel('Parent',tab1,'Title','Spectrogram',...
'unit','norm','outerposition',[0.757 0.41 0.24 0.55],'ShadowColor','k',...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.savfilt=uicontrol('parent',S.ax(1),'style','check','string','Save Filtered Signal Results',...
'unit','norm','Position',[0.841 0.945 0.157 0.06],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman');

%% ================================== Feature Extraction =======================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="blue"><b> Feature Extraction & Wavelet</font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 3 (Optional)','unit',...
'norm','Position',[0.005 0.96 0.39 0.036],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.8 0.8 0.8], 'ForegroundColor','r');
S.L1=uipanel('parent',tab1,'Title','Feature Extraction','unit','norm','Position',...
[0.005 0.41 0.39 0.55],'ShadowColor','k','Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Select Input:','unit','norm','Position',...
[0.01 0.82 0.97 0.18],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Select Input Type:','unit',...
'norm','Position',[0.017 0.22 0.8 0.6],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.inputf=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Input:';...
'Raw Signal';'Flitered Signal'},'unit','norm','Position',[0.5 0.5 0.35 0.4],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.L2=uipanel('parent',S.L1,'Title','Windowing:','unit','norm','Position',[0.01 0.52 0.97 0.3],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.Windw=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Window Type:';...
'Non-Overlapping';'Overlapping'},'unit','norm','Position',[0.015 0.4 0.4 0.5],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Size Window:','unit','norm',...
'Position',[0.005 0.19 0.35 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Novelab=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.225 0.13 0.19 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Sliding Window:','unit','norm',...
'Position',[0.49 0.19 0.46 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.SlidW=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.75 0.13 0.19 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Feature Type:','unit','norm','Position',[0.01 0.17 0.53 0.35],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.TFDomain=uicontrol('parent',S.L2,'style','popupmenu','string',{'Time Domain:'},'unit','norm', ...
'Position',[0.015 0.05 0.76 0.9],'Fontweight','bold','FontSize',11,'FontName','Times New Roman', ...
'HorizontalAlignment','left');
S.FDomain=uicontrol('parent',S.L2,'style','popupmenu','string',{'MNP';'TTP';'MDF';'MNF'},...
'unit','norm','Position',[0.015 0 0.76 0.6],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.TDomain=uicontrol('parent',S.L2,'style','popupmenu','string',{'Mean';'Std';'Median';'ACC';...
'DASDV';'MAD';'MAV';'MMAV';'MFL';'MYOP';'Integrate';'RMS';'SSI';'SSC';'ZC';'VAR';'Skewness';...
'Kurtosis';'V-Order2';'V-Order3';'WAMP';'WL'},'unit','norm','Position',[0.015 0 0.76 0.6],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Threshold:','unit','norm','Position',...
[0.015 0.03 0.6 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.thr=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.426 0.03 0.35 0.25],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.L2=uipanel('parent',S.L1,'Title','Plot','unit','norm','Position',[0.01 0.023 0.53 0.15],...
'BorderWidth',2,'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.display1=uicontrol('parent',S.L2,'style','radio','string','Display Plot','unit',...
'norm','Position',[0.025 0.2 0.8 0.73],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
S.L2=uipanel('parent',S.L1,'Title','Save & Delete Feature:','unit','norm','Position',...
[0.55 0.025 0.43 0.49],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.save=uicontrol('parent',S.L2,'style','pushbutton','string','Save Feature','unit',...
'norm','Position',[0.09 0.65 0.75 0.25],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.delete=uicontrol('parent',S.L2,'style','pushbutton','string','Delete Feature',...
'unit','norm','Position',[0.09 0.31 0.75 0.25],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.list2=uicontrol('parent',S.L2,'style','popupmenu','string','Selection','unit','norm',...
'Position',[0.09 0 0.75 0.25],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.ax(2)=uipanel('Parent',tab1,'Title','Figure Feature Extraction','unit','norm',...
'outerposition',[0.4 0.6 0.6 0.4],'ShadowColor','k','Fontweight','bold','FontSize',...
12,'FontName','Times New Roman','BorderWidth',2);
S.savfea=uicontrol('parent',S.ax(2),'style','checkbox','string','Save Feature Extraction Results',...
'unit','norm','Position',[0.7 0.945 0.3 0.06],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman');

%% ======================================== Wavelet ============================================
S.t1=uicontrol('parent',tab1,'style','text','string','Step 4 (Optional)','unit','norm','Position',...
[0.005 0.37 0.39 0.036],'Fontweight','bold','FontSize',16,'FontName','Times New Roman',...
'BackgroundColor',[0.8 0.8 0.8], 'ForegroundColor','r');
S.L1=uipanel('parent',tab1,'Title','Wavelet','unit','norm','Position',[0.005 0 0.39 0.37],...
'ShadowColor','k','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Select Input:','unit','norm','Position',[0.01 0.75 0.98 0.25],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Select Input Type:','unit','norm',...
'Position',[0.01 0.2 0.6 0.5],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.inputw=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Input:';'Raw Signal';...
'Flitered Signal';'Feature Signal'},'unit','norm','Position',[0.41 0.35 0.35 0.5],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.L2=uipanel('parent',S.L1,'Title','Approximation & Detial','unit','norm','Position',...
[0.01 0.45 0.98 0.3],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Wavelet Type:','unit','norm',...
'Position',[0.01 0.08 0.8 0.65],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Nwavelet=uicontrol('parent',S.L2,'style','popupmenu','string',{'haar';'db2';'db3';'db4';...
'db5';'db6';'db7';'db8';'db9';'db10';'coif1';'coif2';'coif3';'coif4';'coif5';'sym2';'sym3';...
'sym4';'sym5';'sym6';'sym7';'sym8';'fk4';'fk6';'fk8';'fk14';'fk18';'fk22';'bior1.1';'bior1.3';...
'bior1.1';'bior1.3';'bior1.5';'bior2.2';'bior2.4';'bior2.6';'bior2.8';'bior3.1';'bior3.3';...
'bior3.5';'bior3.7';'bior3.9';'bior4.4';'bior5.5';'bior6.8';'rbio1.1';'rbio1.3';'rbio1.5';...
'rbio2.2';'rbio2.4';'rbio2.6';'rbio2.8';'rbio3.1';'rbio3.3';'rbio3.5';'rbio3.7';'rbio3.9';...
'rbio4.4';'rbio5.5';'rbio6.8'},'unit','norm','Position',[0.25 0.4 0.18 0.4],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L2,'style','text','string','Level:','unit','norm','Position',...
[0.7 0.08 0.8 0.65],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.nlevel=uicontrol('parent',S.L2,'style','popupmenu','string',{'1';'2';'3';'4';'5';...
'6';'7';'8';'9';'10';'11';'12'},'unit','norm','Position',[0.82 0.3 0.15 0.5],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','De-noise','unit','norm','Position',[0.01 0.02 0.65 0.42],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Threshold selection Rule:','unit',...
'norm','Position',[0.01 0.45 0.57 0.42],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.THR=uicontrol('parent',S.L2,'style','popupmenu','string',{'rigrsure';'heursure';...
'sqtwolog';'minimaxi'},'unit','norm','Position',[0.6 0.45 0.3 0.42],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Threshold Type:','unit','norm',...
'Position',[0.01 0.08 0.38 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left','Tooltip','s:Soft; h:Hard');
S.softhard=uicontrol('parent',S.L2,'style','popupmenu','string',{'s';'h'},'unit','norm',...
'Position',[0.6 0.01 0.3 0.42],'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left','Tooltip','s:Soft; h:Hard');
S.L2=uipanel('parent',S.L1,'Title','Plot','unit','norm','Position',[0.67 0.02 0.32 0.42],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.Plotwavelet=uicontrol('parent',S.L2,'style','radio','string','Display Plot','unit',...
'norm','Position',[0.05 0.2 0.8 0.73],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left','value',0);
tabgp=uitabgroup(tab1,'Position',[0.4 0 0.6 0.6]);
tab1 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="k"><b>Approximation & Detial</font></html>');
S.ax(3)=uipanel('Parent',tab1,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'k','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab4 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4 color="blue"><b>De-noise</font></html>');
S.ax(4)=uipanel('Parent',tab4,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'b','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.savwav=uicontrol('parent',S.ax(4),'style','checkbox','string','Save De-noise Results','unit','norm',...
'Position',[0.78 0.945 0.22 0.06],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.savwavAD=uicontrol('parent',S.ax(3),'style','checkbox','string','Save Coefficients','unit','norm',...
'Position',[0.82 0.945 0.17 0.06],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');

%% ================================= Classifiation & Clustring =================================
tab1=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="green"><b> Classification & Clustring </font></html>');
S.t1=uicontrol('parent',tab1,'style','text','string','Step 5','unit','norm',...
'Position',[0.005 0.96 0.48 0.036],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.8 0.8 0.8]);
S.t1=uicontrol('parent',tab1,'style','text','string','Training Data Results Display',...
'unit','norm','Position',[0.5 0.96 0.5 0.036],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.8 0.8 0.8],'ForegroundColor','k');
S.L1=uipanel('parent',tab1,'Title','Classification & Clustring','unit','norm',...
'Position',[0.005 0.004 0.48 0.96],'ShadowColor','k','Fontweight','bold',...
'FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.L2=uipanel('parent',S.L1,'Title','Select Input:','unit','norm','Position',...
[0.01 0.895 0.5 0.1],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Select Input Type:','unit','norm',...
'Position',[0.018 0.13 0.8 0.65],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.inputCC=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Input:';'Raw Signal';...
'Flitered Signal';'Feature Signal';'Wavelet Signal'},'unit','norm','Position',[0.48 0.38 0.48 0.49],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.L2=uipanel('parent',S.L1,'Title','Lables','unit','norm','Position',[0.01 0.72 0.5 0.17],...
'Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.Lals=uicontrol('parent',S.L2,'style','popupmenu','string','Slecet Labels:','unit','norm',...
'Position',[0.018 0.54 0.45 0.38],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.NSC=uicontrol('parent',S.L2,'style','popupmenu','string','Select Ch:','unit','norm','Position',...
[0.56 0.54 0.4 0.38],'Fontweight','bold','FontSize',11,'FontName','Times New Roman','enable','off');
S.t1=uicontrol('parent',S.L2,'style','text','string','Chi:','unit','norm','Position',[0.018 0 0.4 0.36],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.NumClass=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.18 0.08 0.23 0.36],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','Value>0','enable','off');
S.t1=uicontrol('parent',S.L2,'style','text','string','Chj:','unit','norm','Position',...
[0.57 0 0.4 0.36],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.NumClass1=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.73 0.08 0.23 0.36],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','Value>0','enable','off');
S.L2=uipanel('parent',S.L1,'Title','Cross Validation','unit','norm','Position',...
[0.01 0.555 0.5 0.16],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.L2,'style','text','string','Select validation Type:','unit',...
'norm','Position',[0.018 0.25 0.55 0.62],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.valid=uicontrol('parent',S.L2,'style','popupmenu','string','kfold','unit','norm',...
'Position',[0.6 0.28 0.36 0.62],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Number Iteration:','unit','norm',...
'Position',[0.018 0 0.4 0.36],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Kfold=uicontrol('parent',S.L2,'style','edit','string','3','unit','norm','Position',...
[0.6 0.08 0.36 0.36],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','Value>1');
S.L2=uipanel('parent',S.L1,'Title','Dimension Reduction (Optional):','unit','norm','Position',...
[0.01 0.01 0.5 0.54],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2, 'ForegroundColor', 'r', 'ShadowColor',[0.4 0.4 0.4]);
S.reduct=uicontrol('parent',S.L2,'style','popupmenu','unit','norm','string',{'Select Method Type:';...
'Feature Extraction Algorithms (FEA)';'Feature Selection Algorithms (FSA)'},'Position',...
[0.018 0.66 0.935 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L2,'style','text','string','Number Features:','unit','norm',...
'Position',[0.018 0.52 0.6 0.28],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Nfeat=uicontrol('parent',S.L2,'style','edit','string','','unit','norm','Position',...
[0.6 0.73 0.35 0.09],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.L3=uipanel('parent',S.L2,'Title','Feature Extraction Algorithms (FEA):','unit','norm',...
'Position',[0.01 0.46 0.98 0.23],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L3,'style','text','string','Select Reduction Type:','unit',...
'norm','Position',[0.018 0.15 0.8 0.5],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.redfeat=uicontrol('parent',S.L3,'style','popupmenu','string',{'PCA';'FDA'},'unit',...
'norm','Position',[0.6 0.3 0.36 0.4],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.L3=uipanel('parent',S.L2,'Title','Feature Selection Algorithms (FSA):','unit','norm',...
'Position',[0.01 0.02 0.98 0.43],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L3,'style','text','string','Select Algorithm Type:','unit',...
'norm','Position',[0.018 0.35 0.8 0.5],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.redfeat1=uicontrol('parent',S.L3,'style','popupmenu','string',{'Ttest';'anova';'MI';'FDR'},...
'unit','norm','Position',[0.59 0.5 0.37 0.4],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.L3,'style','text','string','Alpha:','unit','norm','Position',...
[0.018 0.18 0.65 0.35],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.alpha=uicontrol('parent',S.L3,'style','edit','string','0.01','unit','norm','Position',...
[0.59 0.35 0.37 0.22],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.L3,'style','text','string','Bin:','unit','norm','Position',...
[0.018 0.02 0.4 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.bin=uicontrol('parent',S.L3,'style','edit','string','30','unit','norm','Position',...
[0.59 0.05 0.37 0.22],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.L2=uipanel('parent',S.L1,'Title','Priority List of Features:','unit','norm','Position',...
[0.515 0.2 0.48 0.19],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
Nfeat1=uitable(S.L2,'position',[4 4 286 97],'FontSize',10);
S.L2=uipanel('parent',S.L1,'Title','Best Features Selection:','unit','norm','Position',...
[0.515 0.01 0.48 0.19],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
Nfeat2=uitable(S.L2,'position',[4 4 286 97],'FontSize',10);
S.L2=uipanel('parent',S.L1,'Title','Classification & Clustring Type:','unit','norm',...
'Position',[0.515 0.84 0.48 0.15],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','BorderWidth',2);
S.Classify=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Claasification:';...
'Claasification:'},'unit','norm','Position',[0.018 0.45 0.93 0.45],'Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
% S.Classify=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Claasification OR Clusstering:';...
% 'Claasification:';'Clusstering:'},'unit','norm','Position',[0.018 0.45 0.93 0.45],'Fontweight',...
% 'bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.Cluster1=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Clustering Type:';'SOFM';...
'K-Means';'FCM'},'unit','norm','Position',[0.018 0.03 0.93 0.45],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.Cluster=uicontrol('parent',S.L2,'style','popupmenu','string',{'Select Classification Type:';...
'MLP';'Baysian';'SVM';'KNN';'LVQ';'LDA';'RBF';'PNN';'ELM';'PCA';'DT'},'unit','norm','Position',...
[0.018 0.03 0.93 0.45],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
%  SVM
S.p10=uipanel('parent',S.L1,'Title','Parameters SVM','unit','norm','Position',...
[0.515 0.75 0.48 0.09],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p10,'style','text','string','Select Kernel Function:','unit',...
'norm','Position',[0.018 0.4 0.811 0.4],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.KernalSVM=uicontrol('parent',S.p10,'style','popupmenu','string',{'linear';'gaussian';'rbf';...
'polynomial';'mysigmoid'},'unit','norm','Position',[0.57 0.545 0.38 0.36],'Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
% LDA
S.p8=uipanel('parent',S.L1,'Title','Parameters LDA','unit','norm','Position',...
[0.515 0.75 0.48 0.09],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p8,'style','text','string','Select Metods:','unit','norm',...
'Position',[0.018 0.4 0.811 0.4],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.lda=uicontrol('parent',S.p8,'style','popupmenu','string',{'linear';'diaglinear';...
'pseudolinear';'quadratic';'diagquadratic';'pseudoquadratic'},'unit','norm','Position',...
[0.55 0.545 0.4 0.364],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
% Bayesian
S.p11=uipanel('parent',S.L1,'Title','Parameters Bayesian','unit','norm','Position',...
[0.515 0.75 0.48 0.09],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p11,'style','text','string','Select Distribution Names:','unit',...
'norm','Position',[0.018 0.4 0.811 0.4],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Bay=uicontrol('parent',S.p11,'style','popupmenu','string',{'kernel';'mn';'mvmn';'normal'},...
'unit','norm','Position',[0.64 0.545 0.31 0.364],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
%RBF
S.p30=uipanel('parent',S.L1,'Title','Parameters RBF','unit','norm','Position',...
[0.515 0.69 0.48 0.15],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p30,'style','text','string','Type centers:','unit','norm',...
'Position',[0.018 0.5 0.6 0.327],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.cent=uicontrol('parent',S.p30,'style','popupmenu','string',{'Kmeans';'Rand'},'unit','norm',...
'Position',[0.55 0.53 0.39 0.364],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.t1=uicontrol('parent',S.p30,'style','text','string','Number Neurons:','unit','norm',...
'Position',[0.018 0.2 0.6 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.nrbf=uicontrol('parent',S.p30,'style','edit','string','15','unit','norm','Position',...
[0.55 0.13 0.39 0.35],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
% Kmeans & Fcm
S.p21=uipanel('parent',S.L1,'Title','Parameters Kmeans & Fcm','unit','norm',...
'Position',[0.515 0.68 0.48 0.16],'Fontweight','bold','FontSize',12,'FontName',...
'Times New Roman','BorderWidth',2);
S.t1=uicontrol('parent',S.p21,'style','text','string','Select Distance:','unit','norm',...
'Position',[0.018 0.56 0.57 0.3],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.diskmean=uicontrol('parent',S.p21,'style','popupmenu','string',{'sqeuclidean';...
'cityblock';'cosine';'correlation'},'unit','norm','Position',[0.59 0.6 0.36 0.3],...
'Fontweight','bold','FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.p21,'style','text','string','Number Iteration:','unit','norm',...
'Position',[0.018 0.08 0.6 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Iterkmean=uicontrol('parent',S.p21,'style','edit','string','500','unit','norm','Fontweight',...
'bold','FontSize',11,'FontName','Times New Roman','Position',[0.59 0.13 0.36 0.35]);
% PNN
S.p29=uipanel('parent',S.L1,'Title','Parameters PNN','unit','norm','Position',...
[0.515 0.64 0.48 0.2],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.val=uicontrol('parent',S.p29,'style','radio','string','Normalize Input','unit','norm',...
'Position',[0.018 0.7 0.65 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left','value',1);
S.t1=uicontrol('parent',S.p29,'style','text','string','Type:','unit','norm','Position',...
[0.018 0.32 0.6 0.3],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.typ=uicontrol('parent',S.p29,'style','popupmenu','string',{'Euclidean';'Correlation'},...
'unit','norm','Position',[0.565 0.45 0.38 0.22],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.p29,'style','text','string','Sigma:','unit','norm','Position',...
[0.018 0.045 0.6 0.219],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.sigm=uicontrol('parent',S.p29,'style','edit','string','0.1','unit','norm','Position',...
[0.565 0.05 0.38 0.25],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
% ELM
S.p31=uipanel('parent',S.L1,'Title','Parameters ELM','unit','norm','Position',...
[0.515 0.59 0.48 0.25],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p31,'style','text','string','Active Function:','unit','norm',...
'Position',[0.018 0.68 0.78 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.activefun=uicontrol('parent',S.p31,'style','popupmenu','string',{'Sigmoid';'Tanh'},...
'unit','norm','Position',[0.56 0.75 0.39 0.18],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.p31,'style','text','string','Weights:','unit','norm',...
'Position',[0.018 0.4 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.weights=uicontrol('parent',S.p31,'style','popupmenu','string',{'randn';'rand'},...
'unit','norm','Position',[0.56 0.5 0.39 0.15],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p31,'style','text','string','Number Neurons:','unit','norm',...
'Position',[0.018 0.07 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.NNue=uicontrol('parent',S.p31,'style','edit','string','12','unit','norm','Position',...
[0.56 0.12 0.39 0.22],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
% KNN
S.p12=uipanel('parent',S.L1,'Title','Parameters KNN','unit','norm','Position',...
[0.515 0.59 0.48 0.25],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p12,'style','text','string','Select Method:','unit',...
'norm','Position',[0.018 0.67 0.744 0.2],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.MKnn=uicontrol('parent',S.p12,'style','popupmenu','string',{'kdtree';'exhaustive'},...
'unit','norm','Position',[0.56 0.68 0.39 0.23],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.p12,'style','text','string','Select Distance:','unit','norm',...
'Fontweight','bold','FontSize',11,'Position',[0.018 0.38 0.744 0.2],'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Knndist=uicontrol('parent',S.p12,'style','popupmenu','string',{'cityblock';'chebychev';...
'euclidean';'minkowski'},'unit','norm','Position',[0.56 0.38 0.39 0.23],'Fontweight','bold',...
'FontSize',11,'FontName','Times New Roman','HorizontalAlignment','left');
S.t1=uicontrol('parent',S.p12,'style','text','string','Num Neighbors:','unit','norm',...
'Position',[0.018 0.09 0.589 0.194],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Nneigh=uicontrol('parent',S.p12,'style','edit','string','3','unit','norm','Position',...
[0.56 0.12 0.39 0.22],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'Tooltip','Value>1');
% LVQ
S.p32=uipanel('parent',S.L1,'Title','Parameters LVQ','unit','norm','Position',...
[0.515 0.5 0.48 0.34],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p32,'style','text','string','Learning Fun:','unit','norm',...
'Position',[0.017 0.71 0.78 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.learnfun=uicontrol('parent',S.p32,'style','popupmenu','string',{'learnlv1';'learnlv2'},...
'unit','norm','Position', [0.6 0.8 0.35 0.15],'Fontweight','bold','FontSize',11,....
'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p32,'style','text','string','Num Neurons:','unit','norm',...
'Position',[0.017 0.52 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Nonedim=uicontrol('parent',S.p32,'style','edit','string','10','unit','norm','Position',...
[0.6 0.63 0.35 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p32,'style','text','string','Learning Rate:','unit','norm',...
'Position',[0.017 0.35 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.learnR=uicontrol('parent',S.p32,'style','edit','string','0.01','unit','norm','Position',...
[0.6 0.45 0.35 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p32,'style','text','string','Epochs:','unit','norm',...
'Position',[0.017 0.17 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.epoc=uicontrol('parent',S.p32,'style','edit','string','50','unit','norm','Position',...
[0.6 0.27 0.35 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p32,'style','text','string','Max Fail:','unit','norm',...
'Position',[0.017 0 0.75 0.2],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.maxf=uicontrol('parent',S.p32,'style','edit','string','8','unit','norm','Position',...
[0.6 0.08 0.35 0.15],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
% SOFM
S.p22=uipanel('parent',S.L1,'Title','Parameters SOFM','unit','norm','Position',...
[0.515 0.39 0.48 0.45],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.p45=uipanel('parent',S.p22,'Title','Number Neurons','unit','norm','Position',...
[0.02 0.619 0.965 0.35],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p45,'style','text','string','Num Neurons one Dimension:',...
'unit','norm','Position',[0.017 0.641 0.75 0.219],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman','HorizontalAlignment','left');
S.Nonedim1=uicontrol('parent',S.p45,'style','edit','string','10','unit','norm','Position',...
[0.78 0.562 0.211 0.344],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p45,'style','text','string','Num Neurons two Dimension:',...
'unit','norm','Position',[0.017 0.25 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.Nonedim2=uicontrol('parent',S.p45,'style','edit','string','10','unit','norm','Position',...
[0.78 0.188 0.211 0.344],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.p45=uipanel('parent',S.p22,'Title','eta0 & tau & epochs','unit','norm','Position',...
[0.031 0.053 0.71 0.566],'Fontweight','bold','FontSize',12,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p45,'style','text','string','eta0:','unit','norm','Position',...
[0.023 0.796 0.316 0.124],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Eta=uicontrol('parent',S.p45,'style','edit','string','0.8','unit','norm','Position',...
[0.35 0.77 0.288 0.177],'Fontweight','bold','FontSize',11,'FontName','Times New Roman','Tooltip',...
'0<eta0<1');
S.t1=uicontrol('parent',S.p45,'style','text','string','Tau:','unit','norm','Position',...
[0.023 0.584 0.316 0.124],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Tau=uicontrol('parent',S.p45,'style','edit','string','2000','unit','norm','Position',...
[0.35 0.549 0.288 0.177],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p45,'style','text','string','Epochs:','unit','norm','Position',...
[0.023 0.354 0.316 0.124],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Epoch=uicontrol('parent',S.p45,'style','edit','string','1000','unit','norm','Position',...
[0.35 0.33 0.288 0.177],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p45,'style','text','string','Sig0:','unit','norm','Position',...
[0.023 0.11 0.316 0.124],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Sig=uicontrol('parent',S.p45,'style','edit','string','1.2','unit','norm','Position',...
[0.35 0.1 0.288 0.177],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
% MLP
S.p33=uipanel('parent',S.L1,'Title','Parameters MLP','unit','norm','Position',...
[0.515 0.39 0.48 0.45],'Fontweight','bold','FontSize',12,'FontName','Times New Roman',...
'BorderWidth',2);
S.t1=uicontrol('parent',S.p33,'style','text','string','Learning Fun:','unit','norm',...
'Position',[0.018 0.75 0.7 0.219],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.lfmlp=uicontrol('parent',S.p33,'style','popupmenu','string',{'trainlm';'trainbr'},...
'unit','norm','Position',[0.6 0.83 0.35 0.15],'Fontweight','bold','FontSize',11,...
'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Transfer fun output:','unit','norm',...
'Position',[0.018 0.63 0.7 0.219],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.TFun=uicontrol('parent',S.p33,'style','popupmenu','string',{'purelin';'softmax'},'unit',...
'norm','Position',[0.6 0.71 0.35 0.15],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Num hidden Layers:','unit','norm',...
'Position',[0.018 0.505 0.75 0.219],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.Numhl=uicontrol('parent',S.p33,'style','edit','string','1','unit','norm','Position',...
[0.6 0.64 0.35 0.1],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Num Neurons Layer 1:','unit','norm',...
'Position',[0.018 0.46 0.65 0.14],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.NNhmlp=uicontrol('parent',S.p33,'style','edit','string','10','unit','norm','Position',...
[0.6 0.515 0.35 0.1],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Num Neurons Layer 2:','unit','norm',...
'Position',[0.018 0.33 0.65 0.14],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.NNhmlp1=uicontrol('parent',S.p33,'style','edit','string','10','unit','norm','Position',...
[0.6 0.386 0.35 0.1],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Num Neurons Layer 3:','unit','norm',...
'Position',[0.018 0.196 0.6 0.14],'Fontweight','bold','FontSize',11,'FontName','Times New Roman',...
'HorizontalAlignment','left');
S.NNhmlp2=uicontrol('parent',S.p33,'style','edit','string','5','unit','norm','Position',...
[0.6 0.255 0.35 0.1],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Epochs:','unit','norm',...
'Position',[0.018 0.07 0.6 0.14],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.epocmlp=uicontrol('parent',S.p33,'style','edit','string','100','unit','norm','Position',...
[0.6 0.13 0.35 0.1],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
S.t1=uicontrol('parent',S.p33,'style','text','string','Max Fail:','unit','norm',...
'Position',[0.018 0.015 0.5 0.08],'Fontweight','bold','FontSize',11,'FontName',...
'Times New Roman','HorizontalAlignment','left');
S.maxfmlp=uicontrol('parent',S.p33,'style','edit','string','10','unit','norm','Position',...
[0.6 0.01 0.35 0.1],'Fontweight','bold','FontSize',11,'FontName','Times New Roman');
tabgp=uitabgroup(tab1,'Position',[0.49 0.5 0.515 0.465]);
tab6 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="red"><b>K-Fold Cross Validation</font></html>');
S.ax(5)=uipanel('Parent',tab6,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'r','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab7 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="blue"><b>Partition Data for K-Fold CV </font></html>');
S.ax(6)=uipanel('Parent',tab7,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'b','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab7 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="green"><b>Acc & Sen & Spe</font></html>');
S.ax(7)=uipanel('Parent',tab7,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'g','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab8 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="k"><b>Acc & Sen & Spe & Pre & FM & MCC</font></html>');
S.ax(8)=uipanel('Parent',tab8,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'k','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
S.t1=uicontrol('parent',tab1,'style','text','string','Test Data Results Display','unit',...
'norm','Position',[0.5 0.465 0.5 0.036],'Fontweight','bold','FontSize',16,'FontName',...
'Times New Roman','BackgroundColor',[0.8 0.8 0.8],'ForegroundColor','k');
tabgp=uitabgroup(tab1,'Position',[0.49 0 0.51 0.467]);
tab6 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="red"><b>K-Fold Cross Validation</font></html>');
S.ax(9)=uipanel('Parent',tab6,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'r','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab7 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="blue"><b>Partition Data for K-Fold CV </font></html>');
S.ax(10)=uipanel('Parent',tab7,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'b','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab7 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color=green"><b>Acc & Sen & Spe</font></html>');
S.ax(11)=uipanel('Parent',tab7,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'g','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);
tab8 = uitab(tabgp,'Title','<html><font name="Times New Roman" size=4.5 color="k"><b>Acc & Sen & Spe & Pre & FM & MCC</font></html>');
S.ax(12)=uipanel('Parent',tab8,'unit','norm','outerposition',[0 0 1 1],'ShadowColor',...
'k','Fontweight','bold','FontSize',12,'FontName','Times New Roman','BorderWidth',2);

%% ======================================= uicontextmenu =======================================
cm=uicontextmenu;uimenu('parent',cm,'label','Save','callback',@Save);
uimenu('parent',cm,'label','New Figure','callback',@NewFigure);
uimenu('parent',cm,'label','Subplot','callback',@Subplot);

cmm=uicontextmenu;C2=uimenu('parent',cmm,'label','FontSize');uimenu('parent',C2,'label','8','callback',@FontSize);
uimenu('parent',C2,'label','10','callback',@FontSize);uimenu('parent',C2,'label','12','callback',@FontSize);
uimenu('parent',C2,'label','14','callback',@FontSize);C3=uimenu('parent',cmm,'label','FontWeight');
uimenu('parent',C3,'label','normal','callback',@FontWeight);uimenu('parent',C3,'label','bold','callback',@FontWeight);
C4=uimenu('parent',cmm,'label','xLabel');uimenu('parent',C4,'label','none','callback',@xlab);uimenu('parent',...
C4,'label','Sample','callback',@xlab);uimenu('parent',C4,'label','Time(Sec)','callback',@xlab);
C5=uimenu('parent',cmm,'label','YLabel');uimenu('parent',C5,'label','Amplitude','callback',@ylab);
uimenu('parent',C5,'label','mV','callback',@ylab);uimenu('parent',C5,'label','mu','callback',@ylab);
uimenu('parent',C5,'label','Enter Name','callback',@ylab);

CM=uicontextmenu;C1=uimenu('parent',CM,'label','Color');uimenu('parent',C1,'label','r','callback',@Color);
uimenu('parent',C1,'label','b','callback',@Color);uimenu('parent',C1,'label','g','callback',@Color);
uimenu('parent',C1,'label','k','callback',@Color);uimenu('parent',C1,'label','m','callback',@Color);
uimenu('parent',C1,'label','c','callback',@Color);uimenu('parent',C1,'label','y','callback',@Color);
CC=uimenu('parent',CM,'label','Linestyle');uimenu('parent',CC,'label','-','callback',@Linestyle);
uimenu('parent',CC,'label','--','callback',@Linestyle);uimenu('parent',CC,'label','-.','callback',@Linestyle);
uimenu('parent',CC,'label',':','callback',@Linestyle);CCC=uimenu('parent',CM,'label','Marker');
uimenu('parent',CCC,'label','none','callback',@Marker);uimenu('parent',CCC,'label','o','callback',@Marker);
uimenu('parent',CCC,'label','+','callback',@Marker);uimenu('parent',CCC,'label','*','callback',@Marker);
uimenu('parent',CCC,'label','.','callback',@Marker);uimenu('parent',CCC,'label','x','callback',@Marker);
uimenu('parent',CCC,'label','s','callback',@Marker);uimenu('parent',CCC,'label','d','callback',@Marker);
uimenu('parent',CCC,'label','^','callback',@Marker);uimenu('parent',CCC,'label','>','callback',@Marker);
uimenu('parent',CCC,'label','<','callback',@Marker);uimenu('parent',CCC,'label','p','callback',@Marker);
uimenu('parent',CCC,'label','h','callback',@Marker);CCCC=uimenu('parent',CM,'label','MarkerSize');
uimenu('parent',CCCC,'label','2','callback',@MarkerSize);uimenu('parent',CCCC,'label','4','callback',@MarkerSize);
uimenu('parent',CCCC,'label','6','callback',@MarkerSize);uimenu('parent',CCCC,'label','8','callback',@MarkerSize);
uimenu('parent',CCCC,'label','10','callback',@MarkerSize);uimenu('parent',CCCC,'label','12','callback',@MarkerSize);
uimenu('parent',CCCC,'label','14','callback',@MarkerSize);uimenu('parent',CCCC,'label','16','callback',@MarkerSize);
uimenu('parent',CCCC,'label','18','callback',@MarkerSize);uimenu('parent',CCCC,'label','20','callback',@MarkerSize);
CCCCC=uimenu('parent',CM,'label','Linewidth');
uimenu('parent',CCCCC,'label','0.5','callback',@Linewidth);uimenu('parent',CCCCC,'label','1','callback',@Linewidth);
uimenu('parent',CCCCC,'label','1.5','callback',@Linewidth);uimenu('parent',CCCCC,'label','2','callback',@Linewidth);
uimenu('parent',CCCCC,'label','2.5','callback',@Linewidth);uimenu('parent',CCCCC,'label','3','callback',@Linewidth);
uimenu('parent',CCCCC,'label','3.5','callback',@Linewidth);uimenu('parent',CCCCC,'label','4','callback',@Linewidth);

%% =============================================================================================
tab9=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="blue"><b>Help</font></html>');
help(tab9)
tab10=uitab('parent',tg,'Title','<html><font name="Times New Roman" size=5 color="k"><b>Contact</font></html>');
contact(tab10)

%% =========================================== Variables =======================================
Data=0;FF=0;str=0;values=0;Inputch=0;Input=0;DataFilter=0;fs=0;FVal=[];Fstr=[];SW=[];SS=[];
InputWRecons=0;InputWApprox_Detial=[];Input_classification=0;TPerf=[];FTPerf=[];Perfomance=0;KFold=0;
PerfomanceTotal=[];TPerfT=[];Labels=0;Inpuf=0;PerfomanceT=[];PerfomanceTotalT=[];TPe=[];FTP=[];TPer=[];

%% ================================= Setting callbacks =========================================
set(S.load,'callback',{@Load_Callback,S});set(S.text1,'callback',{@Text1_Callback,S});
set(S.radio1,'callback',{@Radio1_Callback,S});set(S.inp,'callback',{@Inp_Callback,S});
set(S.radio,'callback',{@Radio_Callback,S});set(S.input,'callback',{@Input_Callback,S});
set(S.Chi,'Callback',{@CHi_Callback,S});set(S.Chj,'Callback',{@CHj_Callback,S});
set(S.notch,'callback',{@Notch_Callback,S});set(S.Fnotch,'callback',{@FNotch_Callback,S});
set(S.design,'callback',{@Design_Callback,S});set(S.response,'callback',{@Response_Callback,S});
set(S.fs,'callback',{@Fs_Callback,S});set(S.order,'callback',{@Order_Callback,S});
set(S.fl,'callback',{@Fl_Callback,S});set(S.fh,'callback',{@Fh_Callback,S});
set(S.rp,'callback',{@Rp_Callback,S});set(S.rs,'callback',{@Rs_Callback,S});
set(S.window,'callback',{@Window_Callback,S});set(S.display,'callback',{@Display_Callback,S});
set(S.savfilt,'callback',{@Savfilt_Callback,S});

set(S.inputf,'callback',{@InputFea_Callback,S});set(S.Windw,'callback',{@Windw_Callback,S});
set(S.Novelab,'callback',{@Novelab_Callback,S});set(S.SlidW,'callback',{@SlidW_Callback,S});
set(S.TFDomain,'callback',{@TFDOmain_Callback,S});set(S.FDomain,'callback',{@FDomain_Callback,S});
set(S.TDomain,'callback',{@TDomain_Callback,S});set(S.thr,'Callback',{@Thr_Callback,S});
set(S.display1,'callback',{@Display1_Callback,S});set(S.save,'callback',{@Save_Callback,S});
set(S.delete,'callback',{@Delete_Callback,S});set(S.list2,'callback',{@List2_Callback,S});
set(S.savfea,'callback',{@Savfea_Callback,S});

set(S.inputw,'callback',{@Inputw_Callback,S});set(S.Nwavelet,'callback',{@NWavelet_Callback,S});
set(S.nlevel,'callback',{@Nlevel_Callback,S});set(S.THR,'callback',{@ThR_Callback,S});
set(S.softhard,'callback',{@Softhard_Callback,S});set(S.Plotwavelet,'Callback',{@PLotwavelet_Callback,S});
set(S.savwav,'callback',{@Savwav_Callback,S});set(S.savwavAD,'callback',{@SavwavAD_Callback,S});

set(S.inputCC,'callback',{@InputCC_Callback,S});set(S.Lals,'callback',{@LAls_Callback,S});
set(S.NSC,'callback',{@NsC_Callback,S});set(S.NumClass,'callback',{@NUmClass_Callback,S});
set(S.NumClass1,'callback',{@NUmClass1_Callback,S});set(S.valid,'callback',{@Valid_Callback,S});
set(S.Kfold,'callback',{@KFold_Callback,S});set(S.reduct,'callback',{@Reduct_Callback,S});
set(S.Nfeat,'callback',{@NFfeat_Callback,S});set(S.redfeat,'callback',{@Redfeat_Callback,S});
set(S.redfeat1,'callback',{@Redfeat1_Callback,S});set(S.alpha,'callback',{@Alpha_Callback,S});
set(S.bin,'callback',{@Bin_Callback,S});set(S.Classify,'callback',{@CLassify_Callback,S});
set(S.Cluster1,'callback',{@CLuster1_Callback,S});set(S.Cluster,'callback',{@CLuster_Callback,S});
set(S.KernalSVM,'callback',{@KErnalSVM_Callback,S});set(S.lda,'callback',{@Lda_Callback,S});
set(S.Bay,'callback',{@BAy_Callback,S});set(S.cent,'callback',{@Cent_Callback,S});
set(S.nrbf,'callback',{@Nrbf_Callback,S});set(S.diskmean,'callback',{@Diskmean_Callback,S});
set(S.Iterkmean,'callback',{@ITerkmean_Callback,S});set(S.val,'callback',{@Val_Callback,S});
set(S.typ,'callback',{@Typ_Callback,S});set(S.sigm,'callback',{@Sigm_Callback,S});
set(S.activefun,'callback',{@Activefun_Callback,S});set(S.weights,'callback',{@Weights_Callback,S});
set(S.NNue,'callback',{@NNUe_Callback,S});set(S.MKnn,'callback',{@MKNn_Callback,S});
set(S.Knndist,'callback',{@KNndist_Callback,S});set(S.Nneigh,'callback',{@NNeigh_Callback,S});
set(S.learnfun,'callback',{@Learnfun_Callback,S});set(S.Nonedim,'callback',{@NOnedim_Callback,S});
set(S.learnR,'callback',{@LearnR_Callback,S});set(S.epoc,'callback',{@Epoc_Callback,S});
set(S.maxf,'callback',{@Maxf_Callback,S});set(S.Nonedim1,'callback',{@NOnedim1_Callback,S});
set(S.Nonedim2,'callback',{@NOnedim2_Callback,S});set(S.Eta,'callback',{@ETa_Callback,S});
set(S.Tau,'callback',{@TAu_Callback,S});set(S.Epoch,'callback',{@EPoch_Callback,S});
set(S.Sig,'callback',{@SIg_Callback,S});set(S.lfmlp,'callback',{@Lfmlp_Callback,S});
set(S.TFun,'callback',{@TFUn_Callback,S});set(S.Numhl,'callback',{@NUmhl_Callback,S});
set(S.NNhmlp,'callback',{@NNHmlp_Callback,S});set(S.NNhmlp1,'callback',{@NNHmlp1_Callback,S});
set(S.NNhmlp2,'callback',{@NNHmlp2_Callback,S});set(S.epocmlp,'callback',{@Epocmlp_Callback,S});
set(S.maxfmlp,'callback',{@Maxfmlp_Callback,S});

%% ========================================= Step 1 ============================================
function Load_Callback(~,~,handles)
[str,FF,Data,values] = load_data(handles.Lals,handles.inp,handles.text1,list);end
function Radio1_Callback(~, ~, ~)
[Input,Inputch,DataFilter,fs,Inpuf,FVal,Fstr,SW,SS,InputWApprox_Detial,InputWRecons,...
Input_classification,Labels,Perfomance,PerfomanceTotal,PerfomanceT,PerfomanceTotalT,...
TPerf,TPe,TPer,FTP,TPerfT,FTPerf] = clear_parameters(S,list,Nfeat1,Nfeat2);end
function Inp_Callback(~, ~, handles)
[Inputch,DataFilter] = select_input(Data,handles.input,handles.inp,str,values,list,handles.radio,FF);end
function Input_Callback(~,~,handles)
[Input, FVal, Fstr, SW, SS] = select_channels(Inputch,handles.Chi,handles.Chj,handles.input,handles.inp,...
handles.display,handles.inputf,handles.list2,handles.inputw,handles.inputCC);end

%% ======================================== Step 2 =============================================
function Design_Callback(~, ~, handles)
[DataFilter,fs,FVal,Fstr,SW,SS] = data_filtered(Data,Input,handles.fs,handles.fl,handles.fh,handles.rp,...
handles.rs,handles.order,handles.design,handles.response,handles.window,handles.input,...
handles.Chi,handles.Chj,S.ax(1),cm,CM,cmm,handles.display,handles.Fnotch,handles.notch,...
handles.inputf,handles.list2,handles.inputw,handles.inputCC,S.ax(13));end

%% ========================================= Step 3 ============================================
function InputFea_Callback(~,~,handles)
[Inpuf,typTDom,Lwin,SlidWSize] = feature_extraction(Data,DataFilter,Input,S.ax(2),...
handles.inputf,handles.Novelab,handles.TFDomain,handles.Windw,handles.thr,handles.SlidW,...
handles.TDomain,handles.FDomain,handles.input,handles.Chi,handles.Chj,cm,CM,cmm,handles.display1,...
handles.inputw,handles.inputCC);
savval=get(handles.save,'value');
if savval==1;if ~isnan(Inpuf);FVal=[FVal;{Inpuf}];Fstr=[Fstr;typTDom];SW=[SW;Lwin];SS=[SS;SlidWSize];
set(handles.save,'value',0);set(handles.list2,'string',Fstr);end;end;end
function List2_Callback(~, ~, handles)
[FVal,Fstr,SW,SS] = save_delete_feature(Data,FVal,Fstr,SW,SS,Input,handles.inputf,handles.list2,...
handles.Chi,handles.Chj,handles.input,handles.delete,S.ax(2),cm,CM,cmm);end

%% =========================================== Step 4 ==========================================
function NWavelet_Callback(~, ~, handles)
[InputWApprox_Detial,InputWRecons] = wavelet(Data,handles.nlevel,handles.Nwavelet,handles.softhard,handles.THR,...
handles.Plotwavelet,handles.input,handles.Chi,handles.Chj,S.ax(3),S.ax(4),cm,CM,...
cmm,FVal,handles.inputw,DataFilter,Input,handles.inputCC);end

%% ========================================== Step 5 ===========================================
function InputCC_Callback(~, ~, handles)
Input_classification = input_classification_clustering(Input,DataFilter,FVal,InputWRecons,...
handles.inputCC,handles.NSC,handles.Lals,handles.Cluster,handles.Cluster1,handles.Classify,...
handles.Nfeat,S.ax(5),S.ax(6),S.ax(7),S.ax(8),S.ax(9),S.ax(10),S.ax(11),S.ax(12));end
function LAls_Callback(hobj,~,handles)
Labels = labels_classification_clustering(values,FF,handles.inputCC,hobj,str,handles.NSC,handles.Classify,...
handles.Cluster,handles.Cluster1,handles.NumClass,handles.NumClass1);end
function CLassify_Callback(~, ~, handles)
[Perfomance,PerfomanceTotal,PerfomanceT,PerfomanceTotalT,typeNSC,KFold] = classification_clustering(Input_classification,...
Labels,handles.Lals,handles.inputCC,handles.Classify,handles.Cluster, handles.Cluster1,...
handles.Nneigh,handles.Iterkmean,handles.diskmean,handles.Kfold,handles.KernalSVM,handles.Bay,...
handles.MKnn,handles.Knndist,handles.learnfun,handles.learnR,handles.epoc,handles.Nonedim,...
handles.maxf,handles.NNue,handles.weights,handles.activefun,handles.val,handles.lfmlp,...
handles.TFun,handles.maxfmlp,handles.epocmlp,handles.NNhmlp,handles.NNhmlp1,handles.NNhmlp2,...
handles.cent,handles.nrbf,handles.sigm,handles.typ,handles.p8,handles.p10,handles.p11,handles.p12,...
handles.p21,handles.p22,handles.p29,handles.p30,handles.p31,handles.p32,handles.p33,handles.Numhl,...
handles.lda,handles.Nonedim1,handles.Nonedim2,handles.Epoch,handles.Eta,handles.Tau,handles.Sig,...
S.ax(5),S.ax(6),S.ax(9),S.ax(10),handles.reduct,handles.redfeat,handles.redfeat1,handles.Nfeat,...
Nfeat1,Nfeat2,handles.alpha,handles.bin,cm,CM);
if Perfomance~=0
if TPerf==0;TPerf=[];TPe=[];return;else
    TPe=[TPe;sum(PerfomanceT,1)/KFold];
    TPer=[TPer;sum(PerfomanceTotalT,1)/KFold];FTP=[FTP;typeNSC];
    TPerf=[TPerf;sum(Perfomance,1)/KFold];
    TPerfT=[TPerfT;sum(PerfomanceTotal,1)/KFold];FTPerf=[FTPerf;typeNSC];
end
T='Training';Performance(TPe,TPer,FTP,S.ax(7),S.ax(8),cm,T)
T='Test';Performance(TPerf,TPerfT,FTPerf,S.ax(11),S.ax(12),cm,T)
end;end

%% ======================================== Save Figure ========================================
function Save(~,~,~)
axes1=gca;h=get(axes1,'position');fig_new=figure('unit','norm','pos',h,'Visible','off');
axes_new=copyobj(axes1,fig_new);set(axes_new,'unit','norm','outerposition',[.03 .03 .95 .95])
fn=uiputfile({'*.jpg';'*.tif';'*.png';'*.gif';'*.fig'});
if fn~=0;saveas(axes_new,fn);msgbox('Operation Completed');end;close(fig_new)
end

%% ====================================== save Results =========================================
function Savfilt_Callback(~,~,handles)
if get(handles.savfilt,'value')==1
if DataFilter==0;msgbox('Please select Parameters in Block Filtering','','warn');return;end
Output=DataFilter;set(handles.savfilt,'value',0);
end
if get(handles.savfea,'value')==1
if Inpuf==0;msgbox('Please select Parameters in Block Feature Extraction','','warn');return;end    
Output=Inpuf;set(handles.savfea,'value',0);
end
if get(handles.savwav,'value')==1
if InputWRecons==0;msgbox('Please select Parameters in Block Wavelet','','warn');return;end      
Output=InputWRecons;set(handles.savwav,'value',0);
end
if get(handles.savwavAD,'value')==1
if isempty(InputWApprox_Detial);msgbox('Please select Parameters in Block Wavelet','','warn');return;end      
Output=InputWApprox_Detial;set(handles.savwavAD,'value',0);
end

[fn,~,ind]=uiputfile({'*.mat'});
if fn~=0;if ind==1;save(fn,'Output');elseif ind==2;save(fn,'Output','-ascii');end
msgbox('Operation Completed');
end
end

%% ------------------------------------------- YLabel ------------------------------------------
    function ylab(~,~,~)
        t=(get(gcbo,'label'));ax=gca;if strcmp(t,'mu'); ylabel('\mu v');elseif ...
        strcmp(t,'Enter Name');ylabel(inputdlg('Enter Name'));else;ax.YLabel.String=t;end
        ax.FontName='Times New Roman';if~isempty(ax.Legend);ax.Legend.FontSize=8;end
    end

%% --------------------------------------- NewFigure -------------------------------------------
 function NewFigure(~,~,~)
axes1=gco;fig_new=figure('unit','norm','pos',[0.1 0.45 0.7 0.35]);
axes_new=copyobj(axes1,fig_new);set(axes_new,'unit','norm','outerposition',[.03 .03 .95 .95])
 end

%% -------------------------------- Subplot&xlab&FontSize --------------------------------------
   function Subplot(~,~,~)
       if  Data==0;msgbox('Please Load Data','Error Load Data','error');return;end
       axes_orig=gco;set(axes_orig,'unit','norm');fig_new1=figure(2);
       copyobj(axes_orig,fig_new1);
   end
    function xlab(~,~,~);XLAB(Input,fs);end
    function FontWeight(~,~,~);set(gca,'FontWeight',get(gcbo,'label'));ax=gca;
    ax.FontName='Times New Roman';if~isempty(ax.Legend);ax.Legend.FontSize=8;end;end
    function FontSize(~,~,~);set(gca,'FontSize',str2double(get(gcbo,'label')));
    ax=gca;ax.FontName='Times New Roman'; if~isempty(ax.Legend);ax.Legend.FontSize=8;end;end
    function Color(~,~,~);set(gco,'Color',get(gcbo,'label'));end 
    function Linestyle(~,~,~);set(gco,'Linestyle',get(gcbo,'label'));end
    function Marker(~,~,~);set(gco,'Marker',get(gcbo,'label'));end 
    function MarkerSize(~,~,~);set(gco,'MarkerSize',str2double(get(gcbo,'label')));end 
    function Linewidth(~,~,~);set(gco,'Linewidth',str2double(get(gcbo,'label')));end

    %% =================================== Callback ============================================
    function Radio_Callback(~, ~, handles);Inp_Callback(handles.inp,nan,handles);end
    function FNotch_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Notch_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Fs_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Fl_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Fh_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Order_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Rp_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Rs_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Response_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end 
    function Window_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end
    function Display_Callback(~, ~, handles);Design_Callback(handles.design,nan,handles);end
    function CHi_Callback(~, ~, handles);Input_Callback(handles.input,nan,handles);end 
    function CHj_Callback(~, ~, handles);Input_Callback(handles.input,nan,handles);end 
    function TDomain_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function FDomain_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end 
    function TFDOmain_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end 
    function Thr_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function Windw_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function Novelab_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function Delete_Callback(~, ~, handles);List2_Callback(handles.list2,nan,handles);end
    function Save_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function SlidW_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function Display1_Callback(~, ~, handles);InputFea_Callback(handles.inputf,nan,handles);end
    function NsC_Callback(~, ~, handles);LAls_Callback(handles.Lals,nan,handles);end
    function NUmClass_Callback(~, ~, handles);LAls_Callback(handles.Lals,nan,handles);end
    function NUmClass1_Callback(~, ~, handles);LAls_Callback(handles.Lals,nan,handles);end
    function CLuster_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function CLuster1_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NOnedim1_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NOnedim2_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function ITerkmean_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function ETa_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function TAu_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function EPoch_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function SIg_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function BAy_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function KErnalSVM_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function KFold_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Valid_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function MKNn_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NNeigh_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function KNndist_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Diskmean_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function LearnR_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Learnfun_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Epoc_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NOnedim_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Maxf_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end   
    function NNUe_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Weights_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Activefun_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Lfmlp_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function TFUn_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NNHmlp_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NNHmlp1_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NNHmlp2_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end 
    function Maxfmlp_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NUmhl_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Epocmlp_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Cent_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Nrbf_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Val_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Typ_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Sigm_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Lda_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Reduct_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Alpha_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Bin_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Redfeat_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Redfeat1_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function NFfeat_Callback(~, ~, handles);CLassify_Callback(handles.Classify,nan,handles);end
    function Inputw_Callback(~, ~, handles);NWavelet_Callback(handles.Nwavelet,nan,handles);end
    function Nlevel_Callback(~, ~, handles);NWavelet_Callback(handles.Nwavelet,nan,handles);end
    function ThR_Callback(~, ~, handles);NWavelet_Callback(handles.Nwavelet,nan,handles);end
    function Softhard_Callback(~, ~, handles);NWavelet_Callback(handles.Nwavelet,nan,handles);end
    function PLotwavelet_Callback(~, ~, handles);NWavelet_Callback(handles.Nwavelet,nan,handles);end
    function Savfea_Callback(~, ~, handles);Savfilt_Callback(handles.savfilt,nan,handles);end
    function Savwav_Callback(~, ~, handles);Savfilt_Callback(handles.savfilt,nan,handles);end
    function SavwavAD_Callback(~, ~, handles);Savfilt_Callback(handles.savfilt,nan,handles);end
end